// Realistic seed data shaped like FMCSA L&I / SAFER fields
// In production this would hit the live FMCSA API; here it's a representative sample
const FMCSA_BROKERS = [
  {
    mc: "MC-279140",
    dot: "823914",
    name: "Montway Auto Logistics",
    dba: "Montway",
    city: "Des Plaines",
    state: "IL",
    address: "1500 W. Higgins Rd., Suite 100",
    phone: "(888) 666-8929",
    email: "support@montway.example",
    auth_status: "ACTIVE",
    auth_date: "2007-03-12",
    bond: { provider: "Pacific Financial Assoc.", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Great American", liability: 1000000, cargo: 250000 },
    fleet_partners: 14000,
    years: 18,
    rating: 4.7,
    reviews: 12483,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Enclosed", "Door-to-Door", "Dealer Auctions"],
    bio: "One of the largest broker networks by partner volume. Strong consumer reviews; established dealer program with auction integrations."
  },
  {
    mc: "MC-565145",
    dot: "1453221",
    name: "Sherpa Auto Transport",
    dba: "Sherpa",
    city: "Charlotte",
    state: "NC",
    address: "615 S. College St.",
    phone: "(704) 741-0123",
    email: "info@sherpa.example",
    auth_status: "ACTIVE",
    auth_date: "2017-09-04",
    bond: { provider: "JBW Insurance", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Hanover", liability: 1000000, cargo: 250000 },
    fleet_partners: 2400,
    years: 9,
    rating: 4.9,
    reviews: 5210,
    verified: true,
    flagged: false,
    specialties: ["Price Lock", "Enclosed", "White Glove"],
    bio: "Premium price-lock model — quoted price is final. Smaller carrier network but tightly vetted."
  },
  {
    mc: "MC-908721",
    dot: "2734019",
    name: "Easy Auto Ship Brokers",
    dba: "Easy Auto Ship",
    city: "Charlotte",
    state: "NC",
    address: "8520 Crown Crescent Ct.",
    phone: "(888) 230-9834",
    email: "quotes@easyautoship.example",
    auth_status: "ACTIVE",
    auth_date: "2013-01-22",
    bond: { provider: "Lancer Insurance", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Lancer", liability: 1000000, cargo: 250000 },
    fleet_partners: 18000,
    years: 13,
    rating: 4.6,
    reviews: 8341,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Enclosed", "Motorcycle", "Boat"],
    bio: "High volume consumer broker. Mixed reviews on dispatch timing but solid claims handling."
  },
  {
    mc: "MC-1102883",
    dot: "3318422",
    name: "Nexus Vehicle Movers LLC",
    dba: "Nexus Movers",
    city: "Miami",
    state: "FL",
    address: "2150 NW 79th Ave.",
    phone: "(305) 555-0193",
    email: "ops@nexusmovers.example",
    auth_status: "INACTIVE",
    auth_date: "2021-06-15",
    bond: { provider: "—", amount: 0, status: "LAPSED" },
    insurance: { provider: "—", liability: 0, cargo: 0 },
    fleet_partners: 0,
    years: 5,
    rating: 1.4,
    reviews: 412,
    verified: false,
    flagged: true,
    flag_reason: "Bond lapsed 04/2025 · 38 BBB complaints in 90 days · Operating authority revoked",
    specialties: ["—"],
    bio: "FLAGGED. Operating authority revoked by FMCSA. Multiple complaints of double-brokering and price escalation after pickup."
  },
  {
    mc: "MC-432901",
    dot: "1093823",
    name: "AmeriFreight Vehicle Shipping",
    dba: "AmeriFreight",
    city: "Marietta",
    state: "GA",
    address: "1474 Holcomb Bridge Rd.",
    phone: "(678) 254-5006",
    email: "service@amerifreight.example",
    auth_status: "ACTIVE",
    auth_date: "2004-11-30",
    bond: { provider: "Great American", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Great American", liability: 1000000, cargo: 250000 },
    fleet_partners: 9500,
    years: 21,
    rating: 4.8,
    reviews: 9802,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Enclosed", "Military", "Student Discount"],
    bio: "Long-tenured broker with strong discount programs. Heavy in the southeast dealer market."
  },
  {
    mc: "MC-733201",
    dot: "2104577",
    name: "RoadRunner Auto Transport",
    dba: "RoadRunner",
    city: "Chicago",
    state: "IL",
    address: "1431 Opus Pl., Suite 530",
    phone: "(888) 777-2123",
    email: "hello@roadrunner.example",
    auth_status: "ACTIVE",
    auth_date: "2010-05-18",
    bond: { provider: "Pacific Financial", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Travelers", liability: 1000000, cargo: 250000 },
    fleet_partners: 11200,
    years: 16,
    rating: 4.3,
    reviews: 6712,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Dealer Auctions", "Corporate Relo"],
    bio: "Corporate and dealer-heavy broker. Strong auction lane coverage Manheim/ADESA."
  },
  {
    mc: "MC-841120",
    dot: "2503119",
    name: "uShip Brokerage Services",
    dba: "uShip",
    city: "Austin",
    state: "TX",
    address: "205 Brazos St.",
    phone: "(800) 698-7447",
    email: "support@uship.example",
    auth_status: "ACTIVE",
    auth_date: "2011-08-09",
    bond: { provider: "JBW", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Hanover", liability: 1000000, cargo: 250000 },
    fleet_partners: 21000,
    years: 15,
    rating: 4.4,
    reviews: 14210,
    verified: true,
    flagged: false,
    specialties: ["Marketplace", "Open Transport", "Heavy Equipment", "Boat"],
    bio: "Marketplace model — carriers bid, you choose. Best for buyers who want price control."
  },
  {
    mc: "MC-1320199",
    dot: "3902118",
    name: "Apex National Carriers Group",
    dba: "Apex National",
    city: "Las Vegas",
    state: "NV",
    address: "3535 W. Sahara Ave.",
    phone: "(702) 555-0144",
    email: "info@apexnational.example",
    auth_status: "ACTIVE",
    auth_date: "2023-02-14",
    bond: { provider: "—", amount: 75000, status: "PENDING" },
    insurance: { provider: "Progressive", liability: 1000000, cargo: 100000 },
    fleet_partners: 320,
    years: 3,
    rating: 2.8,
    reviews: 184,
    verified: true,
    flagged: true,
    flag_reason: "12 complaints of price increases after booking · Bond claim filed 02/2026",
    specialties: ["Open Transport"],
    bio: "Newer broker. Authority is active but complaint volume is high. Proceed with caution."
  },
  {
    mc: "MC-198322",
    dot: "612089",
    name: "Reliable Carriers Inc.",
    dba: "Reliable Carriers",
    city: "Canton",
    state: "MI",
    address: "41555 Koppernick Rd.",
    phone: "(877) 744-7889",
    email: "contact@reliablecarriers.example",
    auth_status: "ACTIVE",
    auth_date: "1991-04-03",
    bond: { provider: "Great American", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Great American", liability: 1000000, cargo: 1000000 },
    fleet_partners: 600,
    years: 35,
    rating: 4.9,
    reviews: 3120,
    verified: true,
    flagged: false,
    specialties: ["Enclosed Only", "Concours", "Exotic", "Show Cars"],
    bio: "Enclosed-only specialist. Premium pricing, exotic and concours-grade vehicles."
  },
  {
    mc: "MC-672044",
    dot: "1894033",
    name: "SGT Auto Transport Brokers",
    dba: "SGT",
    city: "Royal Palm Beach",
    state: "FL",
    address: "11924 Forest Hill Blvd.",
    phone: "(864) 546-5038",
    email: "info@sgtauto.example",
    auth_status: "ACTIVE",
    auth_date: "2009-07-21",
    bond: { provider: "Pacific Financial", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Berkshire", liability: 1000000, cargo: 250000 },
    fleet_partners: 7400,
    years: 17,
    rating: 4.7,
    reviews: 7204,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Enclosed", "Door-to-Door", "Snowbird"],
    bio: "Strong northeast/Florida snowbird routes. Good communication scores in reviews."
  },
  {
    mc: "MC-1488992",
    dot: "4218005",
    name: "QuickHaul Logistics LLC",
    dba: "QuickHaul",
    city: "Dallas",
    state: "TX",
    address: "8350 N. Central Expy.",
    phone: "(214) 555-0177",
    email: "ops@quickhaul.example",
    auth_status: "ACTIVE",
    auth_date: "2024-01-09",
    bond: { provider: "JBW", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Progressive", liability: 1000000, cargo: 100000 },
    fleet_partners: 480,
    years: 2,
    rating: 3.9,
    reviews: 92,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Expedited"],
    bio: "Newer broker, limited review volume. Authority is clean."
  },
  {
    mc: "MC-1023845",
    dot: "3022114",
    name: "Mercury Auto Transport Brokers",
    dba: "Mercury",
    city: "Boca Raton",
    state: "FL",
    address: "1200 N. Federal Hwy.",
    phone: "(800) 553-1828",
    email: "team@mercuryauto.example",
    auth_status: "ACTIVE",
    auth_date: "2014-10-12",
    bond: { provider: "Lancer", amount: 75000, status: "ACTIVE" },
    insurance: { provider: "Lancer", liability: 1000000, cargo: 250000 },
    fleet_partners: 5800,
    years: 12,
    rating: 4.5,
    reviews: 4901,
    verified: true,
    flagged: false,
    specialties: ["Open Transport", "Enclosed", "Dealer Auctions"],
    bio: "Dealer-heavy operation with consumer side. Decent communication, average pricing."
  }
];

// Live ticker stats
const REGISTRY_STATS = {
  total_licensed_brokers: 27418,
  active_authority: 24902,
  flagged_this_month: 142,
  scam_reports_30d: 387,
  bond_lapses_30d: 64,
  new_authorities_30d: 218,
  quotes_facilitated_24h: 1043,
  last_sync: "2026-04-30 14:22 UTC"
};

// Recent scam alerts
const SCAM_ALERTS = [
  { mc: "MC-1102883", name: "Nexus Vehicle Movers LLC", date: "2026-04-28", reason: "Authority revoked · Double-brokering" },
  { mc: "MC-1456770", name: "TransGo Express Brokers", date: "2026-04-26", reason: "Bond lapsed · 22 unpaid carrier claims" },
  { mc: "MC-1320199", name: "Apex National Carriers Group", date: "2026-04-22", reason: "Price escalation pattern after booking" },
  { mc: "MC-1502991", name: "Coast2Coast Movers Inc.", date: "2026-04-19", reason: "Identity spoofing · Impersonating MC-198322" },
  { mc: "MC-1390028", name: "Skyline Vehicle Logistics", date: "2026-04-15", reason: "FMCSA cease & desist issued" }
];

// Sample reviews
const SAMPLE_REVIEWS = {
  "MC-279140": [
    { author: "M. Chen", date: "2026-04-12", rating: 5, body: "Picked up in Seattle, delivered to Boston in 8 days. Driver called twice with updates. Quote held." },
    { author: "R. Patel", date: "2026-04-04", rating: 4, body: "Smooth process. Took 3 days to assign a carrier but everything else was fine." },
    { author: "Dealer: Sun Toyota", date: "2026-03-28", rating: 5, body: "Use them weekly for auction pickups. Reliable, decent rates." }
  ],
  "MC-565145": [
    { author: "J. Alvarez", date: "2026-04-19", rating: 5, body: "Price-lock guarantee was real — quoted $1,140, paid $1,140. No bait-and-switch." },
    { author: "K. Brown", date: "2026-04-08", rating: 5, body: "Worth the premium. They turned down a bid that didn't meet their carrier standard. Took an extra day but I trusted it." }
  ],
  "MC-1102883": [
    { author: "Anonymous", date: "2026-04-25", rating: 1, body: "Quoted $890, demanded $1,650 in cash on delivery. Refused to release vehicle until paid. Filed BBB complaint." },
    { author: "T. Williams", date: "2026-04-21", rating: 1, body: "Never picked up. No-showed twice. Stopped answering phones." }
  ]
};

window.FMCSA_BROKERS = FMCSA_BROKERS;
window.REGISTRY_STATS = REGISTRY_STATS;
window.SCAM_ALERTS = SCAM_ALERTS;
window.SAMPLE_REVIEWS = SAMPLE_REVIEWS;
